### PR TITLE
Rename the data pvc to media

### PR DESCRIPTION
**Pull request by brujoand**
This changes the data pvc and mountpoint to media, ref #6
I've bumped the major version of the chart as this would be a breaking change

### CODE REVIEW

**Review by blakeblackshear — APPROVED** [review]

**Comment by blakeblackshear** [comment]
Here is what my current PV/PVC looks like for passing to `extraVolumes`. I'm not sure how I would use the persistence section of the helm chart to achieve the same result. I want my media volume to map to an external disk. How are others doing this?

```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate
spec:
  capacity:
    storage: 900Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/frigate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3os-7155
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 900Gi
  volumeName: "frigate"
```

```yaml
    extraVolumes:
      - name: frigate
        persistentVolumeClaim:
          claimName: frigate

    extraVolumeMounts:
      - mountPath: /media/frigate
        name: frigate
```

**Comment by brujoand** [comment]
From what I understand all you would need is this:
```
persistence:
  media:
    enabled: true
    existingClaim: frigate
```

**Comment by blakeblackshear** [comment]
I'm fine to keep using `extraVolumes` and disabling persistence. I'm wondering if that part of the chart is useful for others.

**Comment by billimek** [comment]
Personally, my media mount is an existingClaim on an NFS with a ton of storage. 

I leverage the ‘data’ persistent storage only for the database because it can’t run properly on NFS (which is my media)

**Comment by brujoand** [comment]
Yeah I agree with @billimek on this I think. It's good and in many cases necessary with an actual volume for the DB, but for  storing media an existing volume claim might be the way to go, atleast if you lan to store a lot and for longer periods. I think the optimal approach here is to keep /data but to also allow users to specify where the media output should go. This way you get some convenience of adding a volume, but you're not restricted as to where the data is stored. WDYT?

**Comment by blakeblackshear** [comment]
Personally, I would lean towards directing people to use `extraVolumes` in the readme since there are many different use cases and external storage setups.

**Comment by brujoand** [comment]
Yeah that also works. In any case, I'll close this as it doesn't really solve anything.

**Comment by brainstain** [comment]
I still think it would be nice to have a flag to enable media for the persistence block.  I'll PR it if you want to reopn.

**Pull request closed without merging**
