### PR TITLE
Update PVC mount point

### PR DESCRIPTION
**Pull request by vladimir-babichev**
This PR addresses #6

### CODE REVIEW

**Comment by billimek** [comment]
@vladimir-babichev what do you think about updating this PR to add the `media` PVC and associated files _in addition to_ the existing `data` PVC & files?

This way, the change will be be breaking for any current users of the chart, and I can see a use-case where having both would be useful.

**Comment by vladimir-babichev** [comment]
@billimek In general I don't mind, but can you point me where `/data` folder is used? This folder is always empty in my deployment and I didn't find any references to it in configuraiton.

**Comment by vladimir-babichev** [comment]
Hi all, just a gentle bump.

**Comment by onedr0p** [comment]
> @billimek In general I don't mind, but can you point me where `/data` folder is used? This folder is always empty in my deployment and I didn't find any references to it in configuraiton.

In my `/data` folder I have:

```
frigate.db  frigate.db-shm  frigate.db-wal
```

**Comment by rmarku** [comment]
Just deployed the chart and configured some cams. My data is empty and in medi I have:
```
root@frigate-7f8dc76dc8-rvpv9:/opt/frigate# find / -iname "frigate.db*"
/media/frigate/clips/frigate.db-shm
/media/frigate/clips/frigate.db
/media/frigate/clips/frigate.db-wal
```

**Comment by vladimir-babichev** [comment]
According to [docs](https://blakeblackshear.github.io/frigate/configuration/index#record) and [application code](https://github.com/blakeblackshear/frigate/blob/42410a260cba711c6362d3433342ea8941b46e30/frigate/const.py) frigate uses `/media` folder as default storage location.

@onedr0p @billimek would you mind sharing helm values and the helm chart version you use?

**Comment by onedr0p** [comment]
In my fridge configmap I have the following options set

```
database: 
  path: /data/frigate.db
```

**Comment by billimek** [comment]
I do the same as @onedr0p

**Comment by maxirus** [comment]
Ran into this issue as well since init attempts to modify permissions of `/media/frigate` which breaks setting things like `securityContext.fsGroup`.

I would 2nd @vladimir-babichev's comments that the Helm Chart should closely follow/align with the Project defaults. Update the `major` version to accept this change as it would (potentially) break existing deployments?

**Comment by jhoblitt** [comment]
I am puzzled as to why the chart is mounting a volume as `/data` with no default usage.  Even if the `.db` is manually relocated under `/data`, the clips and recordings are still written under `/media`.

What is required to get this PR merged?

**Comment by jhoblitt** [comment]
Kludge to get persistence of clips/recordings to work without modifying the chart:

```
persistence:
  data:
    enabled: true
extraVolumeMounts:
  - name: data
    mountPath: /media
    subPath: frigate
```

**Comment by gaffneyd4** [comment]
I ran into this weirdness as well and used these two comments to address:

> In my fridge configmap I have the following options set
> 
> ```
> database: 
>   path: /data/frigate.db
> ```

> My config for persisting captures:
> 
> ```yaml
> extraVolumes:
>   - name: media
>     persistentVolumeClaim:
>       claimName: nfs-frigate
> extraVolumeMounts:
>   - name: media
>     mountPath: /media
> ```
> 
> where nfs-frigate is an existing NFS PVC

**Comment by SchoolGuy** [comment]
Ping on this PR. This hit me today and I was completely baffled why all my events and recordings are gone after each day (running openSUSE MicroOS restarts the host every day).

**Comment by thurcombe** [comment]
hello, what is happening with this? been open for years now, all clips are lost on a pod restart, given that /media is where the clips are supposed to be, surely the chart should provide for this? I see a number of issues open so it would be nice to get a clear picture on where this is currently at?

**Comment by potchin** [comment]
+1 on this, having the app and the helm chart disagree about where the app state lives is pretty bad. Bump the major version and merge this already

**Comment by rssnyder** [comment]
The above `extraVolume` and `extraVolumeMounts` solutions break in the latest chart `7.3.0`. When not specifying media persistence an `emptyDir` is created: https://github.com/blakeblackshear/blakeshome-charts/compare/frigate-7.2.0...frigate-7.3.0#diff-fab55a2ebafe0c123d8ab5d0ba00ee633f7fecb3ca7f7e145f5bed59b382ac13R154

And you now cannot avoid mounting a volume `media` to `/media`: https://github.com/blakeblackshear/blakeshome-charts/compare/frigate-7.2.0...frigate-7.3.0#diff-fab55a2ebafe0c123d8ab5d0ba00ee633f7fecb3ca7f7e145f5bed59b382ac13R113-R114

You now need to get rid of your `extra` mounts/volumes and pass your PVC to the media persistence value:
```yaml
persistence:
  media:
    enabled: True
    existingClaim: media
```

I think this PR can be closed now.

**Pull request closed without merging**
